name: 'teradata_to_databricks'
version: '1.0.0'
config-version: 2

profile: 'teradata_to_databricks'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

require-dbt-version: ">=1.0.0"

# Global configurations
vars:
  # Variables used for environment-specific configurations
  is_prod: "{{ target.name == 'databricks' }}"
  raw_database: "{{ target.database }}"

# Model configurations by directory
models:
  teradata_to_databricks:
    # Staging models (direct source mapping)
    staging:
      +materialized: view
      +schema: "{% if var('is_prod') %}raw_data{% else %}staging{% endif %}"
      +tags: ["staging"]
    
    # Intermediate models (business logic)
    intermediate:
      +materialized: ephemeral
      +schema: "{% if var('is_prod') %}intermediate{% else %}intermediate{% endif %}"
      +tags: ["intermediate"]
    
    # Mart models (business entities)
    marts:
      +materialized: table
      +schema: "{% if var('is_prod') %}transformed_data{% else %}marts{% endif %}"
      +tags: ["marts"]
      
      # Core business entities
      core:
        +tags: ["core"]
        
      # Marketing analytics models
      marketing:
        +tags: ["marketing"]

# Seed configurations
seeds:
  teradata_to_databricks:
    +schema: "{% if var('is_prod') %}reference_data{% else %}seeds{% endif %}"
    region_mapping:
      +column_types:
        region_code: varchar
        region_name: varchar
    
    product_category_mapping:
      +column_types:
        category_id: int
        category_name: varchar
        department: varchar

# Snapshot configurations
snapshots:
  teradata_to_databricks:
    +target_schema: "{% if var('is_prod') %}snapshots{% else %}snapshots{% endif %}"
    +strategy: timestamp
    +updated_at: updated_at